import Modal from '@/components/Modal';
import './globals.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ChatAIBtn from '@/components/ChatAIBtn';
import SideBar from '@/components/SideBar';
import Header from '@/components/Header';
import BoardForm from '@/components/BoardForm';

export const metadata = {
  title: 'AI Trello 2.0',
  description: 'Generated by DevWebPro',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-white-gradient min-h-screen min-w-full'>
        <ToastContainer/>
        <ChatAIBtn/>
        <Modal/>
        <BoardForm/>
        <Header/>
        <main className="flex flex-col sm:flex-row gap-8 sm:gap-0 justify-start">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  )
}
