import Modal from '@/components/Modal';
import './globals.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ChatAIBtn from '@/components/ChatAIBtn';

export const metadata = {
  title: 'AI Trello 2.0',
  description: 'Generated by DevWebPro',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-white-gradient min-h-screen min-w-full'>
        <ToastContainer/>
        <ChatAIBtn/>
        {children}
        <Modal/>
        </body>
    </html>
  )
}
